name: Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web/netdrop/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web/netdrop/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node
      - name: Change working directory
        run: cd web/netdrop
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
