name: API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web/netdrop/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web/netdrop/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node
      - name: Install dependencies
        run: cd web/netdrop && npm ci
      - name: Lint web applicatiomn
        run: cd web/netdrop && npm run lint
      - name: Build web application
        run: cd web/netdrop && npm run build
      - name: Build program
        run: cargo build --release
      - name: Run tests
        run: cargo test
